version: '3.5'

services:
  vblog-web: 
    image: 9rubi/vblog-web:0.0.1
    volumes: 
      - ./dist:/usr/src/app/dist
  nginx:
    image: nginx:1.17.6
    ports:
      - 80:80
    volumes:
      - ./dist:/data/vblog
      - ./vblog.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vblog-api
      - vblog-web
    networks:
      - front-end
      - back-end
  vblog-redis:
    image: redis:5.0.7
    ports:
      - 5001:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      back-end:
        aliases:
          - ${REDIS_ALIAS}
  vblog-api:
    image: 9rubi/vblog:0.0.1
    ports:
      - 7080:8080
    networks:
      back-end:
        aliases:
          - ${API_ALIAS}
    depends_on:
      - database
      - vblog-redis
    environment: 
      JAVA_OPTS: '-Dspring.redis.host=${REDIS_ALIAS} -Dspring.redis.open=false -Dspring.redis.database=0 -Dspring.redis.port=6379 -Dspring.redis.password=${REDIS_PASSWORD}  -Dspring.datasource.druid.first.username=root -Dspring.datasource.druid.first.password=${MYSQL_ROOT_PASSWORD} -Dspring.datasource.druid.first.url=jdbc:mysql://${DB_ALIAS}:3306/vblog -Djava.security.egd=file:/dev/./urandom'
  database:
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_unicode_ci',
      '--default-time-zone=+8:00'
    ]     
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    image: hub.c.163.com/library/mysql:5.7.17
    restart: always
    networks:
      back-end:
        aliases:
          - ${DB_ALIAS}
    ports:
      - 5000:3306    
    volumes:
      - mysql-data:/var/lib/mysql
      - ./vblog.sql:/docker-entrypoint-initdb.d/vblog.sql
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge